### ISSUE TITLE
Potential tweaks/improvements

### ISSUE THREAD

**Issue by khobbits** [threadmeup/slack-sdk#7]
I just made a few edits to this to make it more usable for my purposes.
I'm not going to create 6 or 7 separate pull requests, for each of the tweaks in case they don't match with the project goal.

If you like any of the tweaks done, just ask and I'll prepare a pull request for that feature.

https://github.com/khobbits/slack-sdk/commits/master

**Comment by serialworm** [comment]
Please feel free to submit a pr.  All contributions are welcome.

**Comment by khobbits** [comment]
You want a single PR?
